name: Build

on:
  push:
  pull_request:

jobs:
  build-for-testing:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4
      - name: Build app and tests
        run: >-
          xcodebuild -quiet
          -project OutLoud.xcodeproj
          -scheme OutLoud
          -sdk iphoneos
          -destination 'generic/platform=iOS'
          CODE_SIGNING_ALLOWED=NO
          build-for-testing
